# Generated by Django 2.0.13 on 2019-03-28 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190328_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
