# Generated by Django 2.0.13 on 2019-04-18 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190410_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.DateField(blank=True, null=True, verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
    ]
